//Contains food list with thier values with labels in json
export const foods = [
    { name: "chapati", calories: 297, protein: 9, carbs: 49, fat: 4, fiber: 7, sugar: 2 },
    { name: "appam", calories: 120, protein: 2, carbs: 24, fat: 1, fiber: 1, sugar: 1 },
    { name: "bhature", calories: 320, protein: 7, carbs: 50, fat: 12, fiber: 3, sugar: 2 },
    { name: "bhindi sabzi", calories: 90, protein: 2, carbs: 10, fat: 5, fiber: 3, sugar: 3 },
    { name: "chole", calories: 164, protein: 9, carbs: 27, fat: 3, fiber: 8, sugar: 4 },
    { name: "dal", calories: 116, protein: 8, carbs: 20, fat: 1, fiber: 7, sugar: 2 },
    { name: "dhokla", calories: 160, protein: 6, carbs: 30, fat: 4, fiber: 2, sugar: 5 },
    { name: "rice", calories: 130, protein: 3, carbs: 28, fat: 0, fiber: 0.4, sugar: 0 },
    { name: "rajma", calories: 140, protein: 8, carbs: 22, fat: 1, fiber: 6, sugar: 2 },
    { name: "poha", calories: 180, protein: 3, carbs: 30, fat: 6, fiber: 2, sugar: 3 },
    { name: "dosa", calories: 168, protein: 4, carbs: 30, fat: 5, fiber: 2, sugar: 1 },
    { name: "idli", calories: 146, protein: 4, carbs: 28, fat: 1, fiber: 1, sugar: 0 },
    { name: "medu wada", calories: 330, protein: 5, carbs: 30, fat: 20, fiber: 2, sugar: 1 },
    { name: "upma", calories: 192, protein: 4, carbs: 28, fat: 7, fiber: 2, sugar: 1 },
    { name: "oats", calories: 389, protein: 17, carbs: 66, fat: 7, fiber: 10, sugar: 1 },
    { name: "sprouts", calories: 105, protein: 9, carbs: 20, fat: 1, fiber: 4, sugar: 2 },
    { name: "curd", calories: 61, protein: 3, carbs: 4, fat: 3, fiber: 0, sugar: 4 },
    { name: "paneer curry", calories: 265, protein: 14, carbs: 6, fat: 22, fiber: 1, sugar: 3 },
    { name: "sambar", calories: 80, protein: 3, carbs: 10, fat: 2, fiber: 3, sugar: 2 },
    { name: "tea", calories: 1, protein: 0, carbs: 0, fat: 0, fiber: 0, sugar: 0 },
    { name: "tomato", calories: 18, protein: 1, carbs: 4, fat: 0, fiber: 1, sugar: 3 },
    { name: "onion", calories: 40, protein: 1, carbs: 9, fat: 0, fiber: 1, sugar: 4 },
    { name: "lemon", calories: 29, protein: 1, carbs: 9, fat: 0, fiber: 3, sugar: 2 },
    { name: "corn", calories: 86, protein: 3, carbs: 19, fat: 1, fiber: 2, sugar: 6 },
    { name: "pomegranate", calories: 83, protein: 1, carbs: 19, fat: 1, fiber: 4, sugar: 14 },
    { name: "coconut chutney", calories: 150, protein: 2, carbs: 6, fat: 14, fiber: 2, sugar: 2 },
    { name: "green chutney", calories: 30, protein: 1, carbs: 4, fat: 2, fiber: 1, sugar: 1 },
    { name: "aloo shimla mirch", calories: 120, protein: 3, carbs: 18, fat: 7, fiber: 3, sugar: 3 },
    { name: "rajma rice", calories: 180, protein: 10, carbs: 45, fat: 5, fiber: 6, sugar: 3 },
    { name: "puri", calories: 250, protein: 4, carbs: 30, fat: 12, fiber: 2, sugar: 1 }
];